device: "cuda"


main_name: "train_00_20/model_150.pth"

vqvae_name: "train_00/model_100.pth"
pix_name: "train_00/pixnet_150.pth"
obs_name: "train_00/obsnet_150.pth"

# main_name: "train_00_bar_04/model_60.pth"

# vqvae_name: "train_00_bar/model_150.pth"
# pix_name: "train_00_bar/pixnet_300.pth"
# obs_name: "train_00_bar/obsnet_300.pth"

batch_size: 1000

defaults:
    - _self_
    - vqvae: cnn
    - pixel: cnn

optimizer:
    maxiter: 100
    v_des: 20

env:
    seed: 123
    num_eps: 50
    density: 3.0
    speed_limit: 15
    record: False
    name: ""
    render: True
    plot: False  # Visualization of trajectories, slows down simulation and only works when inferencing with Pytorch

hydra:
    run:
        dir: ./configs/hydra_logs