device: "cuda"
train_log_dir: "./logs"

vqvae_name: "train_00_bar/model_150.pth"
pix_name: "train_00_bar/pixnet_300.pth"
obs_name: "train_00_bar/obsnet_300.pth"

train_name: "train_00_bar_04"

num_epoch: 501
batch_size: 6000
learning_rate: 1e-3

defaults:
    - _self_
    - vqvae: cnn
    - pixel: cnn
 
hydra:
    run:
        dir: ./configs/hydra_logs
