device: "cuda"
train_log_dir: "./logs"

vqvae_name: "train_04/model_250.pth"
pix_name: "train_04/pixnet_200.pth"
obs_name: "train_04/obsnet_200.pth"

train_name: "train_04_02"

num_epoch: 501
batch_size: 5000
learning_rate: 1e-3

defaults:
    - _self_
    - vqvae: cnn
    - pixel: cnn
 
hydra:
    run:
        dir: ./configs/hydra_logs
